INSTALL_TARGET_PROCESSES = com.zhihu.ios
ARCHS = arm64e
TARGET = iphone:latest:13

include $(THEOS)/makefiles/common.mk

TWEAK_NAME = Zhihu

Zhihu_FILES = Tweak.x
Zhihu_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/tweak.mk
