include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = ToolBoxSetting

ToolBoxSetting_FILES = TBSRootListController.m
ToolBoxSetting_FRAMEWORKS = UIKit
ToolBoxSetting_PRIVATE_FRAMEWORKS = Preferences
ToolBoxSetting_INSTALL_PATH = /Library/PreferenceBundles
ToolBoxSetting_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
