include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = FLEXingSetting

FLEXingSetting_FILES = FLEXRootListController.m
FLEXingSetting_FRAMEWORKS = UIKit
FLEXingSetting_PRIVATE_FRAMEWORKS = Preferences
FLEXingSetting_LIBRARIES += sparkapplist
FLEXingSetting_INSTALL_PATH = /Library/PreferenceBundles
FLEXingSetting_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
