include $(THEOS)/makefiles/common.mk

BUNDLE_NAME = SSLPinningSetting

SSLPinningSetting_FILES = SSLRootListController.m
SSLPinningSetting_FRAMEWORKS = UIKit
SSLPinningSetting_PRIVATE_FRAMEWORKS = Preferences
SSLPinningSetting_INSTALL_PATH = /Library/PreferenceBundles
SSLPinningSetting_LIBRARIES += sparkapplist
SSLPinningSetting_CFLAGS = -fobjc-arc

include $(THEOS_MAKE_PATH)/bundle.mk
